---
title: "Simbolos Markdown"
author: "Victor Lopez"
date: "2023-01-11"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Símbolos matemáticos - Básico

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Suma | `+`    | $+$              
Resta | `-` | $-$               
Producto | `\cdot` | $\cdot$                     
Producto | `\times` | $\times$ 
División | `\div` | $\div$
Potencia | `a^{x}` | $a^{x}$
Subíndice | `a_{i}` | $a_{i}$
 

## Símbolos matemáticos - Básico

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Fracción | `\frac{a}{b}`    | $\frac{a}{b}$              
Más menos | `\pm` | $\pm$
Raíz n-ésima | `\sqrt[n]{x}` | $\sqrt[n]{x}$
Unión | `cup` | $\cup$                     
Intersección | `\cap` | $\cap$  
OR lógico | `\vee` | $\vee$
AND lógico | `\wedge` | $\wedge$
 
## Símbolos matemáticos - Relaciones

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Igual | `=` | $=$
Aproximado | `\approx` | $\approx$
No igual | `\ne` | $\ne$  
Mayor que | `>` | $>$
Menor que | `<` | $<$
Mayor o igual que | `\ge`    | $\ge$              
Menor o igual que | `\le` | $\le$

## Símbolos matemáticos - Operadores

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Sumatorio | `\sum_{i=0}^{n}` | $\sum_{i=0}^{n}$
Productorio | `\prod_{i=0}^{n}` | $\prod_{i=0}^{n}$
Integral | `\int_{a}^{b}` | $\int_{a}^{b}$  
Unión (grande) | `\bigcup` | $\bigcup$
Intersección (grande) | `\bigcap` | $\bigcap$
OR lógico (grande) | `\bigvee`    | $\bigvee$              
AND lógico (grande) | `\bigwedge` | $\bigwedge$

## Símbolos matemáticos - Delimitadores

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Paréntesis | `()` | $(\ )$
Corchetes | `[]` | $[\ ]$
Llaves | `\{ \}` | $\{\ \}$  
Diamante | `\langle \rangle` | $\langle\ \rangle$
Parte entera por defecto | `\lfloor \rfloor` | $\lfloor\  \rfloor$
Parte entera por exceso | `\lceil \rceil`    | $\lceil\ \rceil$
Espacio en blanco | `hola\ caracola` | $hola\ caracola$
## Símbolos matemáticos - Letras griegas

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Alpha | `\alpha` | $\alpha$
Beta | `\beta` | $\beta$
Gamma | `\gamma \Gamma` | $\gamma\  \Gamma$  
Delta | `\delta \Delta` | $\delta\  \Delta$
Epsilon | `\epsilon` | $\epsilon$
Epsilon | `\varepsilon`    | $\varepsilon$              
Zeta | `\zeta` | $\zeta$

## Símbolos matemáticos - Letras griegas

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Eta | `\eta` | $\eta$
Theta | `\theta \Theta` | $\theta\ \Theta$
Kappa | `\kappa` | $\kappa$  
Lambda | `\lambda \Lambda` | $\lambda\  \Lambda$
Mu | `\mu` | $\mu$
Nu | `\nu`    | $\nu$              
Xi | `\xi \Xi` | $\xi\ \Xi$

## Símbolos matemáticos - Letras griegas

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Pi | `\pi \Pi` | $\pi\ \Pi$
Rho | `\rho` | $\rho$
Sigma | `\sigma \Sigma` | $\sigma\ \Sigma$  
Tau | `\tau` | $\tau$
Upsilon | `\upsilon \Upsilon` | $\upsilon\ \Upsilon$
Phi | `\phi \Phi`    | $\phi\ \Phi$              
Phi | `\varphi` | $\varphi$

## Símbolos matemáticos - Letras griegas

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Chi | `\chi` | $\chi$
Psi | `\psi \Psi` | $\psi\ \Psi$
Omega | `\omega \Omega` | $\omega\ \Omega$ 


## Símbolos matemáticos - Acentos matemáticos

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Gorrito | `\hat{x}` | $\hat{x}$
Barra | `\bar{x}` | $\bar{x}$
Punto 1 | `\dot{x}` | $\dot{x}$
Punto 2 | `\ddot{x}` | $\ddot{x}$ 
Punto 3 | `\dddot{x}` | $\dddot{x}$ 
Tilde | `\tilde{x}` | $\tilde{x}$
Vector | `\vec{x}` | $\vec{x}$

## Símbolos matemáticos - Acentos expansibles

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Gorrito | `\widehat{xyz}` | $\widehat{xyz}$
Barra | `\overline{xyz}` | $\overline{xyz}$
Subrayado | `\underline{xyz}` | $\underline{xyz}$
Llave superior | `\overbrace{xyz}` | $\overbrace{xyz}$ 
Llave inferior | `\underbrace{xyz}` | $\underbrace{xyz}$ 
Tilde | `\widetilde{xyz}` | $\widetilde{xyz}$
Vector | `\overrightarrow{xyz}` | $\overrightarrow{xyz}$

## Símbolos matemáticos - Flechas

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Simple | `\leftarrow \rightarrow` | $\leftarrow\ \rightarrow$
Doble | `\Leftarrow \Rightarrow` | $\Leftarrow\ \Rightarrow$
Simple larga | `\longleftarrow \longrightarrow` | $\longleftarrow\  \longrightarrow$
Doble larga | `\Longleftarrow \Longrightarrow` | $\Longleftarrow\ \Longrightarrow$ 
Doble sentido simple | `\leftrightarrow` | $\leftrightarrow$ 
Doble sentido doble | `\Leftrightarrow` | $\Leftrightarrow$

## Símbolos matemáticos - Flechas

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Doble sentido larga simple | `\longleftrightarrow` | $\longleftrightarrow$
Doble sentido larga doble | `\Longleftrightarrow` | $\Longleftrightarrow$
Mapea | `\mapsto` | $\mapsto$
Arriba | `\uparrow` | $\uparrow$ 
Abajo | `\downarrow` | $\downarrow$ 

## Símbolos matemáticos - Funciones

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Seno | `\sin` | $\sin$
Coseno | `\cos` | $\cos$
Tangente | `\tan` | $\tan$
Arcoseno | `\arcsin` | $\arcsin$ 
Arcocoseno | `\arccos` | $\arccos$ 
Arcotangente | `\arctan` | $\arctan$

## Símbolos matemáticos - Funciones

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Exponencial | `\exp` | $\exp$
Logaritmo | `\log` | $\log$
Logaritmo neperiano | `\ln` | $\ln$
Máximo | `\max` | $\max$ 
Mínimo | `\min` | $\min$ 
Límite | `\lim` | $\lim$


## Símbolos matemáticos - Funciones

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Supremo | `\sup` | $\sup$
Ínfimo | `\inf` | $\inf$
Determinante | `\det` | $\det$
Argumento | `\arg` | $\arg$ 

## Símbolos matemáticos - Otros

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Puntos suspensivos bajos | `\ldots` | $\ldots$
Puntos suspensivos centrados | `\cdots` | $\cdots$
Puntos suspensivos verticales | `\vdots` | $\vdots$
Puntos suspensivos diagonales | `\ddots` | $\ddots$
Cuantificador existencial | `\exists` | $\exists$
Cuantificador universal | `\forall` | $\forall$
Infinito | `\infty` | $\infty$

## Símbolos matemáticos - Otros

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Aleph | `\aleph` | $\aleph$
Conjunto vacío | `\emptyset` | $\emptyset$
Negación | `\neg` | $\neg$
Barra invertida | `\backslash` | $\backslash$
Dollar | `\$` | $\$$ 
Porcentaje | `\%` | $\%$
Parcial | `\partial` | $\partial$

## Símbolos matemáticos - Tipos de letra

Significado |  Código  |  Resultado                                
--------------------|--------------------|--------------------
Negrita | `\mathbf{palabra}` | $\mathbf{palabra}$
Negrita | `\boldsymbol{palabra}` | $\boldsymbol{palabra}$
Negrita de pizarra | `\mathbb{NZQRC}` | $\mathbb{NZQRC}$
Caligráfica | `\mathcal{NZQRC}` | $\mathcal{NZQRC}$
Gótica | `\mathfrak{NZQRC}` | $\mathfrak{NZQRC}$

## Observaciones

- A la hora de componer en el interior de un párrafo una fracción, existen dos formas: adaptada al tamaño del texto,`$\frac{a}{b}$`, que resulta en $\frac{a}{b}$; o a tamaño real, `$\dfrac{a}{b}$`, que da lugar a $\dfrac{a}{b}$.

- Podemos especificar que los delimitadores se adapten a la altura de la expresión que envuelven utilizando `\left` y `\right`. Observad el cambio en el siguiente ejemplo: `$(\dfrac{a}{b})$` y `$\left(\dfrac{a}{b}\right)$` producen, respectivamente $(\dfrac{a}{b})$ y $\left(\dfrac{a}{b}\right)$.

## Matrices

`$$\begin{matrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{matrix}$$`

$$\begin{matrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{matrix}$$

`$$\begin{pmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{pmatrix}$$`

$$\begin{pmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{pmatrix}$$

## Matrices

`$$\begin{vmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{vmatrix}$$`

$$\begin{vmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{vmatrix}$$

`$$\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{bmatrix}$$`

$$\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{bmatrix}$$

## Matrices

`$$\begin{Bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{Bmatrix}$$`

$$\begin{Bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{Bmatrix}$$

`$$\begin{Vmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{Vmatrix}$$`

$$\begin{Vmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{Vmatrix}$$

## Sistema de ecuaciones

`\begin{array}{l}\end{array}` nos produce una tabla alineada a la izquierda. El hecho de introducir el código `\left. \right.` hace que el delimitador respectivo no aparezca.

`$$\left.\begin{array}{l}
ax+by=c\\
ex-fy=g
\end{array}\right\}$$`
    
$$\left.\begin{array}{l}
ax+by=c\\
ex-fy=g
\end{array}\right\}$$

`$$|x|=\left\{\begin{array}{l}
-x & \text{si }x\le 0\\
x & \text{si }x\ge 0
\end{array}\right.$$`
    
$$|x|=\left\{\begin{array}{l}
-x & \text{si }x\le 0\\
x & \text{si }x\ge 0
\end{array}\right.$$

La función `text{}` nos permite introducir texto en fórmulas matemáticas.
