---
title: "Resumenes estadisticos"
author: "Victor Lopez"
date: "2023-01-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Funcion summary()

```{r}
crabs = read.table("../../data/datacrab.txt", header = TRUE)
crabs = crabs[,-1]
summary(crabs)

summary(subset(crabs, color == 3, c("weight", "width")))
```

# Funcion by()

```{r}
# Aplica una funcion a algunas columnas de un dataframe segmentandolas segun los niveles de 
# un factor

by(iris[, c(1,3)], iris$Species, FUN = summary)

# VALORES NA
# datos_completos <- datos[complete.cases(datos),]
# by(datos_completos, datos_completos$grupo, function(x) mean(x$valor))

# datos_sin_NA <- na.omit(datos)
# by(datos_sin_NA, datos_sin_NA$grupo, function(x) mean(x$valor))
```
# Funcion aggregate()

```{r}
# Es equivalente a by() pero se muestra de otra forma

aggregate(cbind(Sepal.Length, Petal.Length)~Species, data = iris, FUN = summary, na.rm = TRUE)
# La ventaja de aggregate es que podemos evitar valores NA usando el parametro na.rm = TRUE

```

